### ISSUE TITLE
Downloads - Change user preferences to use userdetails user prefs service

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/downloads-plugin#1]
@m-r-c commented on [Fri Apr 01 2016](https://github.com/AtlasOfLivingAustralia/maintenance/issues/3)

Biocache preferences currently stored as cookies. They need to be stored against the user in userDetails.

---

@adam-collins commented on [Mon Apr 18 2016](https://github.com/AtlasOfLivingAustralia/maintenance/issues/3#issuecomment-211140583)

https://upsource.ala.org.au/downloads-plugin/review/DP-CR-1

**Comment by djtfmartin** [comment]
Can this be done in such a way that this is a configuration option (leaving the existing behaviour as is) ?
There are other countries using this app who aren't running userDetails.

**Comment by m-r-c** [comment]
Done under https://github.com/AtlasOfLivingAustralia/maintenance/issues/3
