### ISSUE TITLE
Add raw_taxon_name to custom download output

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/downloads-plugin#11]
Should be included for the "taxon" section of the custom download screen.

raw_taxon_name or scientificName (Dwc: scientificName_raw)

to be added in the `fields` param sent to biocache-service.

**Comment by nickdos** [comment]
Code is inspecting http://biocache.ala.org.au/ws/index/fields to get the fields associated with each of the DwC classes. E.g. if a field has `classs: "Taxon"` against it. So only the DwC fields are included. 

IF we want a non DwC class, then we'll need an extra set of config vars to "augment" the list of fields sent to biocache service.

**Comment by M-Nicholls** [comment]
raw_taxon_name has a classs value of "taxon" in the field list http://biocache.ala.org.au/ws/index/fields so maybe some other reason it's not inluded in the download?

**Comment by nickdos** [comment]
I tihnk I found the "other reason":

https://github.com/AtlasOfLivingAustralia/downloads-plugin/blob/master/grails-app/services/au/org/ala/downloads/BiocacheService.groovy#L70

Was excluding any fields with "_raw" in "dwcTerm" value.
