### ISSUE TITLE
Sort exported columns alpha within 'group'

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/downloads-plugin#12]
When exporting many columns (e.g., via custom option), finding ones of relevance in the CSV is hit and miss due to ordering of column headers appearing random. Suggestion that would make life easier for users is to SORT columns alphabetically by header name within export GROUP (e.g., DwC, assertions, environmental intersections, contextual intersections etc).

**Comment by adam-collins** [comment]
Is this still an issue?
