### ISSUE TITLE
Provide explanation of DwC

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/downloads-plugin#14]
On record download page, the popup for "Full Darwin Core" links to the fields defs but a user has said it doesn't explain what it actually is.

Add a one line explanation to popup:
> Darwin Core a standard data exchange format for biodiversity occurrence data

and link to intro page on DwC site.

**Comment by adam-collins** [comment]
DwC links are at the /fields link and in the download.
