### ISSUE TITLE
Checklist option is showing "field guide" on confirmation screen

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/downloads-plugin#19]
On AVH (at least) the checklist option is showing the confirmation screen with wrong text:

![image](https://user-images.githubusercontent.com/532845/31925767-9c4b7ff2-b8d6-11e7-945f-bde42bd4bef3.png)

The text "View the field guide (new window)" should not be shown (and is not a link either).

**Comment by adam-collins** [comment]
Appears working today.
