### ISSUE TITLE
Download DOI page changes

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/downloads-plugin#21]
E.g. https://biocache-test.ala.org.au/download/doi?doi=10.5072%2F63%2FTEST_DOI_5a5411da8e50c

Make the following changes (see screenshot below):
- [ ] Rename "Datasets" to "Attribution"
- [ ] Add column for "provider type" and extract values from collectory URL (using i18n to encode values). E.g. https://collections.ala.org.au/public/show/dp36 - `dp` indicates `data provider`.
- [ ] Substitute any empty license entries with a default license (see @M-Nicholls  for what to use).

<img width="1192" alt="doi_10_5072_63_test_doi_5a5411da8e50c" src="https://user-images.githubusercontent.com/532845/34702854-25d4ebec-f544-11e7-87dd-a0f136e69437.png">

**Comment by adam-collins** [comment]
Table and license in DOI app have since changed.
