### ISSUE TITLE
Remember last reason user selected

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/downloads-plugin#22]
A comment from some users is that they get sick of selecting the reason drop-down so simply chose the first option. 

Fix is to either remember (via cookie) the last selection or else store the most recent selection in the user's profile store in user-details.

**Comment by matthewandrews** [comment]
Might be worth reconsidering the UI - a dropdown needs a series of user actions, whereas a set of radio buttons only needs one click.
