### ISSUE TITLE
Send records download as POST

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/downloads-plugin#24]
There are a few good reasons to do this (discussed in biocache-room on Hipchat). Biocache-service API says it supports POST but I couldn't get it to work manually using PostMan tool, so might need some tweaking in backend (or better docs to show which request headers are required, etc.).

**Comment by ansell** [comment]
The relevant method in biocache-service, which may help with determining the required parameters, is: 

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/4a9e431b4dd8bed575b8ee9e4c86ea00ebf53778/src/main/java/au/org/ala/biocache/web/DownloadController.java#L140

**Comment by adam-collins** [comment]
done
