### ISSUE TITLE
DownloadParams.mintDoi should be configurable

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/downloads-plugin#28]
``DownloadParams.mintDoi`` should be configurable to allow the download plugin to point to either biocache-service-1.x (where DOI downloads are partially implemented, and setting ``mintDoi=true`` breaks the download and stops an email being sent) or biocache-service-2.x (including where we want to allow turning off minting of DOIs for downloads)

Given this issue is vital and time sensitive, I am going to temporarily switch ``DownloadParams.mintDoi`` to ``false`` in code and release a new version so that we can continue to support downloads using biocache-service-1.x target servers.

**Comment by ansell** [comment]
@javier-molina Yesterday you made changes to ala-install and ansible-inventories with new settings, but none to downloads-plugin. The core issue here is that the setting didn't appear to be configurable in any configuration file, as it was hardcoded in ``DownloadParams``. Is there grails magic happening that allows the values in ``DownloadParams`` to be overridden from configuration files or does it also need code changes (and a new release of downloads-plugin)?

**Comment by javier-molina** [comment]
This is work in progress, I haven't committed all the changes yet.

**Comment by ansell** [comment]
I was just clarifying what the commit message on ala-install/ansible-inventories meant:

> DownloadParams.mintDoi should be configurable
> - Now it is.

Seeing ``Now it is.``, seemed to imply it was ready for testing but was just checking on the status here.

**Comment by IuriGarcia** [comment]
Hi, gentlemen.

Besides having the `doi.mintDoi=false` in biocache-hub and biocache-service properties, i cannot use the raw URL to do the downloads. Could i do the downloads accessing `https://biocache.ala.org.au/download/confirm` without depending on DOI links?

**Comment by adam-collins** [comment]
To my knowledge this is done
