### ISSUE TITLE
Workaround to skip the DOI landing page and redirect through

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/downloads-plugin#30]
The DOI landing page has issues related to inconsistent URL handling ( #26 / #29 ). It would be great if the landing page, ``https://biocache-beta.ala.org.au/download/doi?doi=10.xxx/yyyy`` could be avoided and instead use HTTP 302 to redirect users to the official DOI resolver ``https://doi.org/10.xxx/yyyy``, while the URL encoding issues are resolved. This would preserve the functionality for all of the beta emails which users have received including that URL pattern.

**Comment by adam-collins** [comment]
It appears that the redirect is to the doi application not through this plugin anymore.
