### ISSUE TITLE
Pagination broken on My Downloads page

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/downloads-plugin#31]
**Pre-requisites**
You have more than 10 DOIs so pagination s active

**Steps to reproduce**
1. Go to my [downloads page](https://biocache-test.ala.org.au/download/myDownloads?filter=&offset=30&max=10&sort=dateCreated&order=desc
) 
2. Navigate to page 2 or above

**Expected**
A new page is displayed
**Actual**
You end up in page 1 all the time.

**Comment by nickdos** [comment]
I can't reproduce this - both test and prod version show different DOIs for page 1 and page 2 on my account.

**Comment by adam-collins** [comment]
Appears working.
