### ISSUE TITLE
DOI landing page to go to DOI Service

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/downloads-plugin#32]
It is very ambiguous to have a landing page in the download plugin and one in the doi-service.

There should be only one url to access dois in the doi service and its view change accordingly for biocache downloads (specific one) or use the standard one for anything else.

my downloads page should also go to doi-service

Question: My Downloads is a specific page for biocache downloads or eventually there should be a generic My Dois page?

**Comment by adam-collins** [comment]
done
