### ISSUE TITLE
No User-Agent being sent when download-plugin sends users to biocache offline download

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/downloads-plugin#34]
There was a need to implement a security mechanism to block requests to biocache-service for requests without the HTTP ``User-Agent`` header. This caught users of the downloads-plugin due to the way it sends requests to biocache causing browsers not to send a ``User-Agent`` header.

A different method needs to be implemented that causes browsers to send the ``User-Agent`` header so that the security mechanism can be switched on again.

**Comment by adam-collins** [comment]
Obsolete
