### ISSUE TITLE
No User-Agent being sent when downloads-plugin requests biocache /ws/index/fields

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/downloads-plugin#35]
The server side code in ``downloads-plugin`` that is requesting biocache ``/ws/index/fields`` is doing so without sending a ``User-Agent``. This is making it necessary to remove a fix that prevented users from circumventing user agent blocks by sending no ``User-Agent`` header.

**Comment by adam-collins** [comment]
Obsolete
