### ISSUE TITLE
Add Google Analytics integration

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/downloads-plugin#39]
ALA is now tracking the download confirmation page as a "completion" event in GA. It should be possible to send some GA `custom dimensions` ([link](https://developers.google.com/analytics/devguides/collection/analyticsjs/custom-dims-mets)) to GA on the final confirmation page, so that user data can be combined with data we have in biocache - such as download type, download format & reason code.

**Comment by nickdos** [comment]
Page is now including the following JS in the middle of the page:

```
  ga('set', 'dimension2', 'records');
  ga('set', 'dimension3', 'logger.download.reason.testing');
```

Will need to check GA to see if these are being detected there.

**Comment by nickdos** [comment]
After some testing, it seems the data is not being sent to Google due to that code (above) not ebing in the same block as the GA code under the footer.

In order to add the lines above to the GA code, the Grails plugin (`ala-bootstrap3` and probably `commonui-bs-*`) will needed to be jacked-up to pass in the data. TODO

**Comment by adam-collins** [comment]
Obsolete
