### ISSUE TITLE
Remove ShapeFile option

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/downloads-plugin#45]
Occurrence record ShapeFile downloads are causing significant performance issues with biocache-service, due to being an in-memory process. ALA has decided to remove this option as using the CSV output is functionally equivalent, as all data in ShapeFile output are just points.

Plan is to disable the option with a mouse-over popup that explains the reasons and has a link to a support article.

**Comment by matthewandrews** [comment]
I'd suggest some on-page text would be better than a mouse-over popup: touch devices like phone/tablet won't normally get access to mouse-based content, and some screenreaders etc would miss it too.

**Comment by nickdos** [comment]
Fixed  in https://github.com/AtlasOfLivingAustralia/downloads-plugin/commit/1106f6ee1288dbbd5fcf63e469148dc2d191edad

**Comment by adam-collins** [comment]
All configurable now.
