### ISSUE TITLE
tool tip descriptions for downloads controls

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/downloads-plugin#5]
Download export options for the classes of columns is not self-explanatory or documented adequately. Darwin Core classes; species traits (?); spatial intersections (I know but other won't); miscellaneous (??) quality assertions, miscellaneous fields. Need pop-ups?

**Comment by adam-collins** [comment]
Individual optional includes have a rollover with description/link for each.
