### ISSUE TITLE
Allow downloads to handle POST requests

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/downloads-plugin#50]
See AtlasOfLivingAustralia/biocache-hubs/issues/291.

**Comment by nickdos** [comment]
Created branch -> https://github.com/AtlasOfLivingAustralia/downloads-plugin/tree/POST-refactor

which requires changes in biocache-hubs, also in a branch -> https://github.com/AtlasOfLivingAustralia/biocache-hubs/tree/POST-downloads

Changes on hold to get fix for `contraintsMap` param issue deployed.

**Comment by adam-collins** [comment]
linked issue is marked as done
