### ISSUE TITLE
Add configurable option to include species list in downloads

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/downloads-plugin#53]
For custom download form, allow a client app to provide a list of specieslist UIDs (via config) that are included as an optional output type that can be selected by the user.

The additional "lists" should be included at the end of the "Species Traits" section. When selected by the user, the species list UIDs will be appended to the `'fields` (or `extra` - depending on what the code already uses) param. E.g. `fields=id,taxon_name,dr15515`.

@pbrenton - this issue will allow the Wildnet taxon IDs to be included in downloads via the list UID: `dr15515`.

**Comment by nickdos** [comment]
@pbrenton I've done a quick first go at this - do you think having the option available under the "custom download -> other traits" option is too "hidden". The other option is giving it its own selector, which is a bit more work.

![image](https://user-images.githubusercontent.com/532845/81884130-5e8e1380-95da-11ea-9a38-bf5c23176d11.png)

**Comment by pbrenton** [comment]
Thanks Nick,

Having it there is certainly a bit hidden for anyone who might go looking for it and not aware that it is there, but for those concerned, we can just tell them that’s where it is. If it is not logical enough for users we can look at doing more if needed.

Cheers

Peter

**Comment by nickdos** [comment]
Changed to be more obvious - mostly driven by config

![image](https://user-images.githubusercontent.com/532845/81887135-d6ac0780-95e1-11ea-84a4-a8f12e501a99.png)

**Comment by pbrenton** [comment]
Ah, that is good! Thanks Nick

**Comment by nickdos** [comment]
@pbrenton this was deployed today.

**Comment by pbrenton** [comment]
Thanks Nick, much appreciated.
Am I supposed to get an email containing the download file? If so, how long is that supposed to take?
Peter

**Comment by nickdos** [comment]
Yes, you should get an email – depends on the download size… lots of records (>100,000) takes longer, so better to test with a sub-1000 record count search.
