### ISSUE TITLE
Revert dynamic download status updates on confirmation screen

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/downloads-plugin#55]
Plugin used to show user a changing status message about whether download was running or finished and allowed them to click through to the download when done (thus avoiding waiting for email).

See https://github.com/AtlasOfLivingAustralia/downloads-plugin/blob/master/grails-app/views/download/confirm.gsp#L194-L200

**Comment by ansell** [comment]
The setTimeout version also likely has the advantage of waiting to make the call to biocache-service, as there is a small amount of time (1 to 2 seconds) before offline downloads are picked up, registered, and able to be started in some cases. Doing that call synchronously without a sleep is possibly before that process is complete.

**Comment by sylmorin-gbif** [comment]
![issue55](https://user-images.githubusercontent.com/56630013/86326880-9dd3fa80-bc42-11ea-86d3-909aea69d875.gif)
