### ISSUE TITLE
Silent success message with a failed download attempt

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/downloads-plugin#58]
The following fails, presumably because the WKT on the QID is empty:

```
https://biocache-test.ala.org.au/download/confirm?searchParams=q%3Dqid%3A1593408932517&targetUri=%2Foccurrences%2Fsearch%3F&downloadType=records
```

```
https://biocache-ws-test.ala.org.au/ws/qid/1593408932517
```

However, it shows in the interface as a silent success, with an unusable URL that doesn't go anywhere useful.

It also doesn't generate any error messages in the logs on either biocache-test or biocache-ws-test, so it isn't clear where the issue may be without debugging.

Refs ticket 85044 in helpdesk

**Comment by adam-collins** [comment]
Unsure given the issue description. If the search parameters are wrong you cannot click the download button to get to this page.
