### ISSUE TITLE
Species checklist filename

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/downloads-plugin#6]
The UI provides no option to specify the filename and it is using the default filename for the records download option. I suggest it uses a more meaningfulauto-generated filename (e.g. checklist-YYYMMDD.csv)

**Comment by adam-collins** [comment]
I think this is referring to a lack of a filename option for the `Species checklist` and `Species field-guide` options. 

1. Add parameter to fieldguide for a filename
2. Fix usage of `file` parameter in biocache-service's occurrences/facets/download
3. Add the option to the UI
