### ISSUE TITLE
Feature request: Download "tasks" page

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/downloads-plugin#65]
Troubleshooting download issues would be easier with a download history/"tasks" page similar to the Spatial Portal.

- Tool should list all download tasks by date and time, with timestamp, user, query run, status (in progress/completed/failed) and some "history" (ie. query originated in SP or Explore your area) to assist with troubleshooting.
- Searching/sorting tasks by user would be useful for analysing individual users' download history/attempts.

**Comment by adam-collins** [comment]
Given the stability improvements this is no longer necessary.
