### ISSUE TITLE
My Downloads - DQ Profiles

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/downloads-plugin#68]
On the My Downloads page, when I disable all quality filters in my search, the Search Query field still says I have the 'ALA Profile' set, which isn't technically true because I've disabled it.

**disableAllQualityFilters: true
qualityProfile: ALA** 

Should this be fixed?

**Comment by adam-collins** [comment]
Appears fixed. I did a download with filters disabled and it says `Data profile disabled`.
