### ISSUE TITLE
Better inline help

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/downloads-plugin#7]
Some aspects of UI that could benefit with some inline/popup help text:

* records download formats need explanation (what is DarwinCore with link), what is legacy format
* provide a link to page where the fields included for each download type are listed
* change drop-down for the download format list to a radio button widget, so that the user can see all options without having to click on it and we can also provide popup help next to each option (not possible with select widget)
* list the fields returned for the checklist and field guide types

**Comment by m-hope** [comment]
We also need to document (or have a link to a document that) defines what each of the fields mean and represent. This document could be included in the download zip file...

**Comment by adam-collins** [comment]
I think this is done
