### ISSUE TITLE
"Your download is skipped" message is incomplete and confusing

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/downloads-plugin#71]
When a user attempts an impossible download - eg, the entire ALA database - they are shown the following message:

![image](https://user-images.githubusercontent.com/57081387/126730031-36d466f8-f415-4363-9f5e-17bebfac832d.png)

Basically, in place of "Download running" or "Your download is ready", it instead says "Your download is skipped". It does not explain why, and also shows conflicting information about receiving an email once the download is complete.

Suggested changes are, when a download is skipped:

- Explain why the download was skipped (too large a request, etc)
- Change the rest of the displayed text so it does not conflict by referring to things that happen after a successfully completed download operation and "Thank you for your download"

**Comment by adam-collins** [comment]
biocache-service no longer returns the status `skipped`. It will return with `status: too_large` and give the reason in `error` field.

This should be added to `function updateStatus(json)` in `confirm.gsp`.

**Comment by adam-collins** [comment]
Looks like it is already handled by the default.
