### ISSUE TITLE
Feature request: Link to list of downloads from "Your download is ready" page

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/downloads-plugin#72]
This links to a user's list of previous ALA data downloads: https://biocache.ala.org.au/download/myDownloads/

It's linked to only from a user's profile, among a number of other links, and is easily missed. We should add it to the "Your download is ready" message when downloading, so increase its visibility.

**Comment by brucehyslop** [comment]
There's already a link at the bottom of the "Your download is ready" page. 
We could make the link more prominent or move it inside the "dialog" area.

![Screen Shot 2021-11-11 at 9 28 52 am](https://user-images.githubusercontent.com/12233783/141409502-1cdc44a3-6c1b-4fa2-91d9-bcbf0352ef7b.png)

**Comment by adam-collins** [comment]
Link has since changed.
