### ISSUE TITLE
Allow biocache data access for large WKT polygons

### ISSUE THREAD

**Issue by sughics** [AtlasOfLivingAustralia/downloads-plugin#82]
Reported by @peggynewman 

This query gives a 500 error with the GET > 8000 chars.
ALA users should be able to access biocache data using a large polygon. It would be ideal if this could at least be implemented by downloads, if not the UI.

Currently, downloads requests via biocache-hubs UI with a URL length > 8000 chars are being dropped by the [downloads-plugin ](https://github.com/AtlasOfLivingAustralia/downloads-plugin) when attempting to forward the request onto biocache-service. downloads-plugin needs to implement POST request in cases where url length > 8000. [biocache-hubs](https://github.com/AtlasOfLivingAustralia/biocache-hubs) plugin also needs to be updated and subsequently all other hubs(ala, ozcam, asbp, avh) need to be compiled with new version of these plugins

**Comment by adam-collins** [comment]
Pull request https://github.com/AtlasOfLivingAustralia/downloads-plugin/pull/89

Please test with single and multiple fq statements that do an do not contain commas. 
 e.g. `fq=scientificNameAuthorship:"Linnaeus,%201758"&fq=longitude:%5B150.9%20TO%20151%5D`

**Comment by sughics** [comment]
Released with [3.2.0](https://github.com/AtlasOfLivingAustralia/biocache-service/releases/tag/3.2.0)
