### ISSUE TITLE
Improvements to pre-generated downloads.

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/downloads-plugin#85]
<img width="949" alt="Screenshot 2023-05-03 at 3 18 09 pm" src="https://user-images.githubusercontent.com/4197871/235837981-d0607179-3c68-42cd-9dbd-4924ae4d9ba8.png">

**Comment by peggynewman** [comment]
Yikes, we removed those downloads a long time ago. But given the issues we have with downloads, it would be great to make some larger files available.

I suggest we do it again, but create DOIs for the downloads, and do a set of downloads that are open to the public, and a set that requires authenticated access. The data should be refreshed monthly. See https://github.com/gbif/occurrence/blob/master/aws-public-data.md as a nice example of giving public access to this.

Open to the public:
* plants
* mammals
* birds
* insects
* etc - science team, your call (@mjwestgate @shandiya)
* per states / territories
* possibly the current names archive 

Restricted access:
* containing unobfuscated locations etc according to SDS roles - per states/territories
* I'd also like to add external iNaturalist sensitive data to this bucket

**Comment by timrobertson100** [comment]
If it helps to know, all GBIF downloads are listed [here](https://www.gbif.org/occurrence-snapshots).

**Comment by adam-collins** [comment]
Cannot change the link in the on screen message until it exists, and there is no planned date at this time. Closing.
