### ISSUE TITLE
Duplicate field names in downloads

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/downloads-plugin#87]
On the support queue https://support.ehelp.edu.au/a/tickets/174777 someone has reported the location fields are confusing. 

With latitude for example, the download gave them 3 fields: `decimalLatitude`, `verbatimLatitude`, and `verbatimLatitude`. 

Clearly one of the verbatimLatitude fields is actually raw_decimalLatitude. These DwC terms aren’t interchangeable. verbatim fields usually means that pipelines doesn't process them. Also looks like a bit of encoding drama happening with excel there.

![Image](https://user-images.githubusercontent.com/1271932/235585255-0b7aa425-c023-47fc-b5e8-0906af7ce79d.png)

**Comment by sat01a** [comment]
Reported by @peggynewman

**Comment by adam-collins** [comment]
Addressed as part of https://github.com/AtlasOfLivingAustralia/downloads-plugin/issues/83

**Comment by sughics** [comment]
Released with [4.0.0](https://github.com/AtlasOfLivingAustralia/downloads-plugin/releases/tag/4.0.0)
