### ISSUE TITLE
Remove "...may take more than 24 hours to run" message from download page

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/downloads-plugin#98]
This message pops up on a download options page when a search finds more than one million records. This message is vastly out of date (likely it was created early on in the ALA) and our present ability to process records for download under ideal conditions means it is now incorrect.

As an easy test case, all NSW and VIC records of magpies are 1.1m records: https://biocache.ala.org.au/occurrences/search?q=lsid%3Ahttps%3A%2F%2Fbiodiversity.org.au%2Fafd%2Ftaxa%2F5291343e-fdeb-4a65-8ba5-928f5b96acf5&qualityProfile=ALA&qc=-_nest_parent_%3A*&fq=(state%3A%22Victoria%22%20OR%20state%3A%22New%20South%20Wales%22)#tab_recordsView

Some test results are below:

- It takes 5 minutes to process 1 million records to download (with the "ALA Occurrence Download Complete" email appearing two minutes later)
- At this rate, we can process approx. 288 million records for download in a 24 hour period, more than twice what the ALA contains in 2023
- With all possible fields selected in a custom download, it takes 30 minutes to process 1 million records
- At this rate, under ideal conditions, we could process approx. 48 million records for download for a single user in 24 hours

![Image](https://github.com/AtlasOfLivingAustralia/downloads-plugin/assets/57081387/8aee6cdd-4768-4bf9-95b2-706ffd65c5f1)

**Comment by matthewandrews** [comment]
perhaps "may take some time to run" ?

**Comment by adam-collins** [comment]
@peggynewman please comment

**Comment by timhicks-ala** [comment]
> perhaps "may take some time to run" ?

@matthewandrews I like this approach as it does a better job of clearly managing expectations than what's there currently.

**Comment by adam-collins** [comment]
Committed the change, https://github.com/AtlasOfLivingAustralia/downloads-plugin/commit/14526e5e32d5ba108ee5be1c3abd605c739b412b. It will be in the next release, whenever that is.
