### ISSUE TITLE
Remove greyed-out Shapefile download option

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/downloads-plugin#99]
The option to download a Shapefile using Biocache has been disabled since 2019. Whether or not this feature is ever re-implemented, we should remove it from the download options page as it is no longer relevant or current.

It links to this support article, which can be de-published once this option has disappeared: https://support.ala.org.au/support/solutions/articles/6000226357-why-aren-t-shapefile-downloads-available-any-more-

![Image](https://github.com/AtlasOfLivingAustralia/downloads-plugin/assets/57081387/0c2b3f72-5bbe-4712-917e-b8b8cb38d422)

**Comment by kylie-m** [comment]
(Following this issue; I'll unpublish the article once the link to it has been removed)

**Comment by adam-collins** [comment]
Config change pull request https://github.com/AtlasOfLivingAustralia/ala-install/pull/739
